### ISSUE TITLE
PropertyInterceptionInfo not marked as NonSerialized

### ISSUE THREAD

**Issue by ibutra** [Capgemini/Cauldron#50] opened 2017-12-21 15:35 UTC
The added Property PropertyInterceptionInfo is not marked as NonSerialized which makes it impossible to intercept Properties of classes which shall be serialized

**Comment by reflection-emit** [comment] 2017-12-21 15:51
It is actually not a property... It is a field... I will add a NonSerialized attribute to that field.

**Comment by reflection-emit** [comment] 2017-12-21 16:09
Ok... It is added... I'll push and release a new version after I am finished with some documentations.

**Comment by ibutra** [comment] 2017-12-21 17:11
You are of course right it is a field.
And WOW! thank you for that quick reaction and fix.
Keep up the great work

**Comment by reflection-emit** [comment] 2017-12-21 19:55
I also added Newtonsoft.Json.JsonIgnoreAttribute to the list... In case Newtonsoft.Json is referenced in the project.

**Comment by reflection-emit** [comment] 2017-12-21 20:08
Fixed in version 2.0.24 ... The build script has skiped a version... 😄 
Packages are uploading now.

**Closed by reflection-emit** 2017-12-21 20:08 UTC

**Comment by ibutra** [comment] 2017-12-22 12:02
First of all: Thank you for this quick reaction and fix.
Unfortunately I still get the following error:

`System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=Type 'Cauldron.Interception.PropertyInterceptionInfo' in Assembly 'Cauldron.Interception, Version=2.0.0.24, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
`

I tried to clean the solution and rebuild. I even restarted Visual Studio. Something else I am missing?

**Comment by reflection-emit** [comment] 2017-12-22 12:10
Hmmm…. Weird… Can you give more infos please. What are you intercepting a field or a property? How are you serializing the instance?
I have to reproduce the error to build a unit test out of it to avoid such errors in the future.


________________________________

Firma: Capgemini Deutschland GmbH
Aufsichtsratsvorsitzender: Antonio Schnieder • Geschäftsführer: Dr. Michael Schulte (Sprecher) • Jost Förster • Dr. Peter Lempp • Dr. Volkmar Varnhagen

Amtsgericht Berlin-Charlottenburg, HRB 98814
This message contains information that may be privileged or confidential and is the property of the Capgemini Group. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by ibutra** [comment] 2017-12-22 12:15
I will try to minimize it as much as possible to narrow it down and get back to you

**Comment by reflection-emit** [comment] 2017-12-22 12:28
Yes! I am able to reproduce it now… Analysing it now… I’ll push an update as soon as I have fixed it.


________________________________

Firma: Capgemini Deutschland GmbH
Aufsichtsratsvorsitzender: Antonio Schnieder • Geschäftsführer: Dr. Michael Schulte (Sprecher) • Jost Förster • Dr. Peter Lempp • Dr. Volkmar Varnhagen

Amtsgericht Berlin-Charlottenburg, HRB 98814
This message contains information that may be privileged or confidential and is the property of the Capgemini Group. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by ibutra** [comment] 2017-12-22 12:41
In case you still need it, here is my minimal example:

[Repository](https://github.com/ibutra/CauldronMinimalExample)

**Comment by reflection-emit** [comment] 2017-12-22 12:48
Thanks… That confirms that I am in the right track… It is almost the same code I use to reproduce.
So… What I found out… The fields and properties created by Cauldron are all attributed with the NonSerialized Attribute… Seems like it is just ignored.
I am trying to find out why. I have to google a bit.


________________________________

Firma: Capgemini Deutschland GmbH
Aufsichtsratsvorsitzender: Antonio Schnieder • Geschäftsführer: Dr. Michael Schulte (Sprecher) • Jost Förster • Dr. Peter Lempp • Dr. Volkmar Varnhagen

Amtsgericht Berlin-Charlottenburg, HRB 98814
This message contains information that may be privileged or confidential and is the property of the Capgemini Group. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by reflection-emit** [comment] 2017-12-22 13:14
Ok now I got it… The compiler seems to remove the Custom attribute and replace it with an IL feature.
So the result is:
.field private nonserialized class …..
Where my attributes are still custom attributes
.field private class…
.custom instance class [mscorlib]System.NonSerializedAttribute::ctor()


Fixing that right now.


________________________________

Firma: Capgemini Deutschland GmbH
Aufsichtsratsvorsitzender: Antonio Schnieder • Geschäftsführer: Dr. Michael Schulte (Sprecher) • Jost Förster • Dr. Peter Lempp • Dr. Volkmar Varnhagen

Amtsgericht Berlin-Charlottenburg, HRB 98814
This message contains information that may be privileged or confidential and is the property of the Capgemini Group. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by reflection-emit** [comment] 2017-12-22 14:17
Check the newest version please.

**Comment by ibutra** [comment] 2017-12-22 14:28
Thank you, it works now.
